Feat: adding and searching games on DB
cifoteam/gameBoardStats pull request #24
Opened 2023-02-24 10:41 UTC by vcalvache

BoardGame manager has all the test. The BoardGame storage class has the add method, search game and list all games methos implemented.

2023-02-24 21:06 UTC, ProtossGP32 requested changes
Missing classes in this pull request, the branch is not fully synchronized with `main`.

Waiting for the proper merge prior to going on with the review

2023-02-24 21:06 UTC, ProtossGP32 commented on tindergames/src/test/java/org/teamcifo/domain/BoardGameTest.java
> +    }
2 things to comment regarding this method:
- Although being a test, it isn't asserting anything, thus not a test at all
- A similar method called `populateBoardGames` is already defined in the `FakeDataGenerator` class inside the test utils package

Please use the above mentioned method instead, and add some kind of assertion to the test. Check the test `printGamesCollection` in the `GamesCollectionManagerTest` for some inspiration on how to check `System.out` prints

2023-02-27 11:33 UTC, vcalvache commented
Pull request made with a older and not updated version. Proceed to cancel and make a new pull request

2023-02-27 11:42 UTC, ProtossGP32 commented
Reopen PR, waiting for `main` changes merged to branch

2023-02-27 12:27 UTC, ProtossGP32 commented on tindergames/src/test/java/org/teamcifo/domain/BoardGameTest.java
> +    }
Fixed in next commit

2023-02-27 12:36 UTC, ProtossGP32 approved these changes
All changes OK

2023-02-27 12:37 UTC, merged